# Generated by Django 5.0 on 2023-12-14 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativas', models.ManyToManyField(blank=True, to='avance_academico.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materias_aprobadas', models.ManyToManyField(blank=True, related_name='estudiantes_aprobados', to='avance_academico.materia')),
                ('materias_en_curso', models.ManyToManyField(blank=True, related_name='estudiantes_en_curso', to='avance_academico.materia')),
            ],
        ),
    ]
