# Generated by Django 5.0 on 2024-01-24 10:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='0', max_length=200)),
                ('apellido', models.CharField(default='0', max_length=200)),
                ('alta_admin', models.BooleanField()),
                ('carreras', models.ManyToManyField(blank=True, to='avance_academico.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('duracion', models.CharField(blank=True, choices=[('ANUAL', 'ANUAL'), ('PRIMER CUATRIMESTRE', 'PRIMER CUATRIMESTRE'), ('SEGUNDO CUATRIMESTRE', 'SEGUNDO CUATRIMESTRE')], max_length=50, null=True)),
                ('dia', models.CharField(blank=True, choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES'), ('SABADO', 'SABADO')], max_length=50, null=True)),
                ('horario', models.CharField(blank=True, choices=[('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=50, null=True)),
                ('carrera_materia', models.ManyToManyField(blank=True, default='carrera', to='avance_academico.carrera')),
                ('correlativas', models.ManyToManyField(blank=True, to='avance_academico.materia')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCursada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_recursada', models.IntegerField(default=0)),
                ('aprobada', models.BooleanField(default=0)),
                ('en_curso', models.BooleanField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avance_academico.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avance_academico.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('PARCIAL', 'PARCIAL'), ('RECUPERATORIO', 'RECUPERATORIO'), ('FINAL', 'FINAL')], max_length=50, null=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha', models.DateField()),
                ('materia_cursada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avance_academico.materiacursada')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(default='Nombre', max_length=200)),
                ('apellido_profesor', models.CharField(default='Apellido', max_length=200)),
                ('materias', models.ManyToManyField(blank=True, to='avance_academico.materia')),
            ],
        ),
    ]
