# Generated by Django 5.0 on 2023-12-18 11:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='materia',
            name='anio',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='duracion',
            field=models.CharField(blank=True, choices=[('ANUAL', 'ANUAL'), ('PRIMER CUATRIMESTRE', 'PRIMER CUATRIMESTRE'), ('SEGUNDO CUATRIMESTRE', 'SEGUNDO CUATRIMESTRE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(default='0', max_length=200)),
                ('apellido_profesor', models.CharField(default='0', max_length=200)),
                ('materias', models.ManyToManyField(blank=True, to='avance_academico.materia')),
            ],
        ),
    ]
