# Generated by Django 5.0 on 2024-01-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_primer_cuatrimestre', models.DateField()),
                ('fin_primer_cuatrimestre', models.DateField()),
                ('inicio_segundo_cuatrimestre', models.DateField()),
                ('fin_segundo_cuatrimestre', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='materia',
            name='horario',
        ),
        migrations.AddField(
            model_name='carrera',
            name='años',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrera',
            name='materias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrera',
            name='titulo_intermedio',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='fin_horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='inicio_horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
