# Generated by Django 5.0 on 2024-01-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0001_initial'),
    ]

    operations = [


        migrations.AddField(
            model_name='materia',
            name='fin_horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='inicio_horario',
            field=models.TimeField(blank=True, null=True),
        ),


    ]
