# Generated by Django 5.0 on 2023-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
