# Generated by Django 5.0 on 2023-12-14 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='anio',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='duracion',
            field=models.CharField(blank=True, choices=[('ANUAL', 'ANUAL'), ('PRIMER CUATRIMESTRE', 'PRIMER CUATRIMESTRE'), ('SEGUNDO CUATRIMESTRE', 'SEGUNDO CUATRIMESTRE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
