# Generated by Django 5.0 on 2023-12-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0002_materia_anio_materia_codigo_materia_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(default='0', max_length=200)),
                ('apellido_profesor', models.CharField(default='0', max_length=200)),
                ('materias', models.ManyToManyField(blank=True, to='avance_academico.materia')),
            ],
        ),
    ]
