# Generated by Django 5.0 on 2024-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0002_carrera_materia_dia_materia_fin_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_primer_cuatrimestre', models.DateField()),
                ('fin_primer_cuatrimestre', models.DateField()),
                ('inicio_segundo_cuatrimestre', models.DateField()),
                ('fin_segundo_cuatrimestre', models.DateField()),
            ],
        ),
    ]
