# Generated by Django 5.0 on 2024-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0003_configuracionsemestre_materia_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='años',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrera',
            name='materias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrera',
            name='titulo_intermedio',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),

    ]
