# Generated by Django 5.0 on 2024-01-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0003_materia_profesor_alter_profesor_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='profesor',
        ),
    ]
