# Generated by Django 5.0 on 2024-01-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0004_carrera_años_carrera_materias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='horario',
        ),
    ]
