# Generated by Django 5.0 on 2024-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avance_academico', '0005_remove_materia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='avance_academico.materia'),
        ),
    ]
